const linesData = [
    { angle: 0,
     info: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Expedita dignissimos cum suscipit eius. Alias cupiditate sunt corporis iste dolorum, amet reiciendis. Vero delectus ab velit cum consequuntur voluptatem incidunt esse?', 
     titel: 'Titel 1', 
     titelS: 'Titel 1', 
     zIndex: '5', 
     textRot: '-90deg' },
    { angle: 12, info: 'Information 3', titel: 'Titel 1', titelS: 'Titel 1', zIndex: '7', textRot: '-90deg' },
    { angle: 24, info: 'Information 4', titel: 'Titel 1', titelS: 'Titel 1', zIndex: '7', textRot: '-90deg' },
    { angle: 48, info: 'Information 5', titel: 'Titel 2', titelS: 'Titel 1', zIndex: '1', textRot: '-90deg' },
    { angle: 60, info: 'Information 6', titel: 'Titel 2', titelS: 'Titel 1', zIndex: '3', textRot: '-90deg' },
    { angle: 72, info: 'Information 7', titel: 'Titel 2', titelS: 'Titel 1', zIndex: '5', textRot: '-90deg' },
    { angle: 84, info: 'Information 8', titel: 'Titel 2', titelS: 'Titel 1', zIndex: '7', textRot: '-90deg' },
    { angle: 96, info: 'Information 9', titel: 'Titel 2', titelS: 'Titel 1', zIndex: '7', textRot: '-90deg' },
    { angle: 120, info: 'Information 10', titel: 'Titel 3', titelS: 'Titel 1', zIndex: '1', textRot: '-90deg' },
    { angle: 132, info: 'Information 11', titel: 'Titel 3', titelS: 'Titel 1', zIndex: '3', textRot: '-90deg' },
    { angle: 144, info: 'Information 12', titel: 'Titel 3', titelS: 'Titel 1', zIndex: '5', textRot: '-90deg' },
    { angle: 156, info: 'Information 13', titel: 'Titel 3', titelS: 'Titel 1', zIndex: '7', textRot: '-90deg' },
    { angle: 168, info: 'Information 14', titel: 'Titel 3', titelS: 'Titel 1', zIndex: '7', textRot: '-90deg' },
    { angle: 192, info: 'Information 15', titel: 'Titel 4', titelS: 'Titel 1', zIndex: '1', textRot: '90deg' },
    { angle: 204, info: 'Information 16', titel: 'Titel 4', titelS: 'Titel 1', zIndex: '3', textRot: '90deg' },
    { angle: 216, info: 'Information 17', titel: 'Titel 4', titelS: 'Titel 1', zIndex: '5', textRot: '90deg' },
    { angle: 228, info: 'Information 18', titel: 'Titel 4', titelS: 'Titel 1', zIndex: '7', textRot: '90deg' },
    { angle: 240, info: 'Information 19', titel: 'Titel 4', titelS: 'Titel 1', zIndex: '7', textRot: '90deg' },
    { angle: 264, info: 'Information 20', titel: 'Titel 5', titelS: 'Titel 1', zIndex: '1', textRot: '90deg' },
    { angle: 276, info: 'Information 21', titel: 'Titel 5', titelS: 'Titel 1', zIndex: '3', textRot: '90deg' },
    { angle: 288, info: 'Information 22', titel: 'Titel 5', titelS: 'Titel 1', zIndex: '5', textRot: '90deg' },
    { angle: 300, info: 'Information 23', titel: 'Titel 5', titelS: 'Titel 1', zIndex: '7', textRot: '90deg' },
    { angle: 312, info: 'Information 24', titel: 'Titel 5', titelS: 'Titel 1', zIndex: '7', textRot: '90deg' },
    { angle: 336, info: 'Information 25', titel: 'Titel 1', titelS: 'Titel 1', zIndex: '1', textRot: '90deg' },
    { angle: 348, info: 'Information 1', titel: 'Titel 1', titelS: 'Titel 1', zIndex: '3', textRot: '90deg' },
];